import { useEffect, useState } from 'react'
import { RefreshCw } from 'lucide-react'
import type {
  AIBackend, AIBackendId, AIConfig, AIMode, AIResourceMode, AppConfig, CustomProviderConfig,
} from '../../shared/types'
import { nyx, usePalette } from '../palette/PaletteProvider'
import { useStore } from '../state/store'
import {
  NyxButton, NyxCard, NyxCardHeader, NyxChip, NyxDropdown, NyxSettingRow, NyxStatus, NyxSwitch,
  NyxTextField,
} from '../components/nyx'

type PaletteSource = AppConfig['palette']['source']

const PROVIDER_LABELS: Record<string, string> = {
  matugen: 'Matugen', pywal: 'pywal', wallust: 'Wallust', end4: 'end-4',
}

export function Settings() {
  const config = useStore((s) => s.config)
  const patchConfig = useStore((s) => s.patchConfig)
  const { snapshot, providers, reload } = usePalette()

  const setPalette = (patch: Partial<AppConfig['palette']>) =>
    void patchConfig({ palette: { ...config.palette, ...patch } })

  return (
    <div className="h-full overflow-y-auto p-5">
      <header className="mb-4">
        <h1 style={{ color: nyx('textPrimary') }} className="text-xl font-semibold tracking-tight">Settings</h1>
        <p style={{ color: nyx('textMuted') }} className="mt-0.5 text-xs">
          Stored in ~/.config/nyxium/config.json
        </p>
      </header>

      <div className="grid max-w-3xl grid-cols-1 gap-4">
        <NyxCard>
          <NyxCardHeader title="Appearance" />
          <div className="px-3.5">
            <NyxSettingRow title="Theme" description="Light mode follows the palette's own mode when dynamic colors are on.">
              <NyxDropdown
                value={config.theme}
                onChange={(theme) => void patchConfig({ theme })}
                options={[
                  { value: 'system', label: 'System' },
                  { value: 'dark', label: 'Dark' },
                  { value: 'light', label: 'Light' },
                ]}
              />
            </NyxSettingRow>
            <NyxSettingRow title="Density" description="Controls padding across lists and cards.">
              <NyxDropdown
                value={config.density}
                onChange={(density) => void patchConfig({ density })}
                options={[
                  { value: 'compact', label: 'Compact' },
                  { value: 'comfortable', label: 'Comfortable' },
                  { value: 'spacious', label: 'Spacious' },
                ]}
              />
            </NyxSettingRow>
            <NyxSettingRow title="Reduced motion" description="Disables transitions and animations.">
              <NyxSwitch
                checked={config.reducedMotion}
                label="Reduced motion"
                onChange={(reducedMotion) => void patchConfig({ reducedMotion })}
              />
            </NyxSettingRow>
          </div>
        </NyxCard>

        <NyxCard>
          <NyxCardHeader
            title="Dynamic colors"
            action={
              <NyxButton size="sm" variant="ghost" icon={<RefreshCw size={12} />} onClick={() => void reload()}>
                Reload Palette
              </NyxButton>
            }
          />
          <div className="px-3.5">
            <NyxSettingRow title="Enabled" description="Follow the system palette generated by your wallpaper tool.">
              <NyxSwitch
                checked={config.palette.enabled}
                label="Dynamic colors"
                onChange={(enabled) => setPalette({ enabled })}
              />
            </NyxSettingRow>
            <NyxSettingRow title="Source" description="Auto picks the first detected provider.">
              <NyxDropdown<PaletteSource>
                value={config.palette.source}
                onChange={(source) => setPalette({ source })}
                options={[
                  { value: 'auto', label: 'Auto' },
                  { value: 'matugen', label: 'Matugen' },
                  { value: 'pywal', label: 'pywal' },
                  { value: 'wallust', label: 'Wallust' },
                  { value: 'end4', label: 'end-4' },
                  { value: 'manual', label: 'Manual' },
                ]}
              />
            </NyxSettingRow>
            <div style={{ borderColor: nyx('outlineVariant') }} className="border-b py-3">
              <div style={{ color: nyx('textPrimary') }} className="mb-2 text-sm">Detected providers</div>
              <ul className="flex flex-col gap-1.5">
                {providers.map((p) => (
                  <li key={p.id} className="flex items-center justify-between gap-3">
                    <NyxStatus tone={p.available ? 'success' : 'idle'}>{PROVIDER_LABELS[p.id] ?? p.id}</NyxStatus>
                    <span style={{ color: nyx('textMuted') }} className="truncate font-mono text-[11px]">
                      {p.path ?? 'not found'}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="py-3">
              <div style={{ color: nyx('textPrimary') }} className="mb-2 text-sm">Custom palette paths</div>
              <p style={{ color: nyx('textMuted') }} className="mb-3 text-xs">
                Override auto-detection. Takes priority over the built-in candidate paths.
              </p>
              <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
                {(['matugen', 'pywal', 'wallust', 'end4'] as const).map((id) => (
                  <NyxTextField
                    key={id}
                    label={PROVIDER_LABELS[id]}
                    value={config.palette.customPaths[id] ?? ''}
                    placeholder="~/.cache/…/colors.json"
                    onChange={(e) =>
                      setPalette({
                        customPaths: { ...config.palette.customPaths, [id]: e.target.value || undefined },
                      })}
                  />
                ))}
              </div>
            </div>
          </div>
        </NyxCard>

        <NyxCard>
          <NyxCardHeader title="Active palette" />
          <div className="p-3.5">
            {snapshot ? (
              <>
                <div className="mb-3 grid grid-cols-2 gap-x-6 gap-y-1.5 text-xs">
                  <Row label="Provider" value={snapshot.provider} />
                  <Row label="Mode" value={snapshot.mode} />
                  <Row label="Source" value={snapshot.source} span />
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {(['background', 'surface', 'surfaceVariant', 'primary', 'secondary', 'tertiary',
                     'success', 'warning', 'error', 'info'] as const).map((key) => (
                    <div key={key} className="flex flex-col items-center gap-1">
                      <span
                        title={`${key} · ${snapshot.colors[key]}`}
                        style={{ background: snapshot.colors[key], borderColor: nyx('outline') }}
                        className="size-9 rounded-lg border"
                      />
                      <span style={{ color: nyx('textMuted') }} className="text-[9px]">{key}</span>
                    </div>
                  ))}
                </div>
              </>
            ) : (
              <span style={{ color: nyx('textMuted') }} className="text-xs">Loading palette…</span>
            )}
          </div>
        </NyxCard>

        <AISettings />

        <NyxCard>
          <NyxCardHeader title="Keyboard shortcuts" />
          <div className="p-3.5">
            <ul className="grid grid-cols-1 gap-1.5 sm:grid-cols-2">
              {[
                ['Ctrl + K', 'Command palette'],
                ['Ctrl + P', 'Global search'],
                ['Ctrl + B', 'Toggle sidebar'],
                ['Ctrl + T', 'New tab'],
                ['Ctrl + W', 'Close tab'],
                ['Ctrl + Shift + T', 'Restore closed tab'],
                ['Ctrl + `', 'Terminal'],
                ['Ctrl + Shift + S', 'Snippets'],
                ['Ctrl + Shift + A', 'AI Agent'],
                ['Ctrl + ,', 'Settings'],
              ].map(([keys, action]) => (
                <li key={keys} className="flex items-center justify-between gap-3">
                  <span style={{ color: nyx('textSecondary') }} className="text-xs">{action}</span>
                  <kbd
                    style={{ background: nyx('surfaceVariant'), color: nyx('textPrimary'), borderColor: nyx('outlineVariant') }}
                    className="rounded border px-1.5 py-0.5 font-mono text-[10px]"
                  >
                    {keys}
                  </kbd>
                </li>
              ))}
            </ul>
          </div>
        </NyxCard>
      </div>
    </div>
  )
}

/** Local AI configuration. No API key field exists anywhere — local mode never needs one. */
function AISettings() {
  const [cfg, setCfg] = useState<AIConfig | null>(null)
  const [backends, setBackends] = useState<AIBackend[]>([])
  const [busy, setBusy] = useState(false)

  const probe = async () => {
    setBusy(true)
    setBackends(await window.nyx.ai.detect())
    setBusy(false)
  }

  useEffect(() => {
    void window.nyx.ai.config().then(setCfg)
    void probe()
  }, [])

  const patch = async (p: Partial<AIConfig>) => setCfg(await window.nyx.ai.patchConfig(p))

  if (!cfg) return null
  const active = backends.find((b) => b.id === cfg.provider)

  return (
    <NyxCard>
      <NyxCardHeader
        title="Local AI"
        action={
          <NyxButton size="sm" variant="ghost" icon={<RefreshCw size={12} />} loading={busy} onClick={() => void probe()}>
            Detect
          </NyxButton>
        }
      />
      <div className="px-3.5">
        <NyxSettingRow title="Local AI enabled" description="Inference runs on this machine. Nyxium never sends code to a hosted model.">
          <NyxSwitch checked={cfg.enabled} label="Local AI" onChange={(enabled) => void patch({ enabled })} />
        </NyxSettingRow>

        <NyxSettingRow title="Provider" description="Ollama, a llama.cpp server, or any local OpenAI-compatible endpoint.">
          <NyxDropdown<AIBackendId>
            value={cfg.provider}
            onChange={(provider) => void patch({ provider })}
            options={[
              { value: 'ollama', label: 'Ollama' },
              { value: 'llamacpp', label: 'llama.cpp' },
              { value: 'openai-compatible', label: 'OpenAI-compatible' },
              { value: 'custom', label: cfg.custom.label || 'Custom endpoint' },
            ]}
          />
        </NyxSettingRow>

        <div style={{ borderColor: nyx('outlineVariant') }} className="border-b py-3">
          <div style={{ color: nyx('textPrimary') }} className="mb-2 text-sm">Detected backends</div>
          <ul className="flex flex-col gap-1.5">
            {backends.map((b) => (
              <li key={b.id} className="flex items-center justify-between gap-3">
                <NyxStatus tone={b.available ? 'success' : 'idle'}>{b.label}</NyxStatus>
                <span style={{ color: nyx('textMuted') }} className="truncate font-mono text-[11px]">{b.endpoint}</span>
              </li>
            ))}
          </ul>
          {!backends.some((b) => b.available) ? (
            <p style={{ color: nyx('textMuted') }} className="mt-2 text-xs">
              No local inference server detected. Nyxium stays fully usable without one.
            </p>
          ) : null}
        </div>

        <div style={{ borderColor: nyx('outlineVariant') }} className="border-b py-3">
          <div style={{ color: nyx('textPrimary') }} className="mb-2 text-sm">Local endpoints</div>
          <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
            {(['ollama', 'llamacpp', 'openai-compatible'] as AIBackendId[]).map((id) => (
              <NyxTextField
                key={id}
                label={id === 'llamacpp' ? 'llama.cpp' : id === 'ollama' ? 'Ollama' : 'OpenAI-compatible'}
                value={cfg.endpoints[id]}
                onChange={(e) => void patch({ endpoints: { ...cfg.endpoints, [id]: e.target.value } })}
              />
            ))}
          </div>
        </div>

        <CustomProvider cfg={cfg} onPatch={patch} onProbe={probe} />

        <NyxSettingRow title="Model" description={active?.available ? 'Pick one in AI Agent → Models.' : 'Available once a backend is reachable.'}>
          <span style={{ color: nyx('textPrimary') }} className="font-mono text-xs">{cfg.model ?? 'none selected'}</span>
        </NyxSettingRow>

        <NyxSettingRow title="Agent mode" description="Ask explains, Plan proposes, Agent asks before changes, Trusted Agent pre-approves routine ones.">
          <NyxDropdown<AIMode>
            value={cfg.mode}
            onChange={(mode) => void patch({ mode })}
            options={[
              { value: 'ask', label: 'Ask' },
              { value: 'plan', label: 'Plan' },
              { value: 'agent', label: 'Agent' },
              { value: 'trusted', label: 'Trusted Agent' },
            ]}
          />
        </NyxSettingRow>

        <NyxSettingRow title="Resource mode" description="Low RAM caps context at 4K and allows one request at a time.">
          <NyxDropdown<AIResourceMode>
            value={cfg.resourceMode}
            onChange={(resourceMode) => void patch({ resourceMode })}
            options={[
              { value: 'performance', label: 'Performance' },
              { value: 'balanced', label: 'Balanced' },
              { value: 'low-ram', label: 'Low RAM' },
            ]}
          />
        </NyxSettingRow>

        <NyxSettingRow title="Context size" description="Tokens of context requested from the model.">
          <NyxTextField
            type="number"
            value={cfg.contextSize}
            onChange={(e) => void patch({ contextSize: Math.max(512, Number(e.target.value) || 512) })}
          />
        </NyxSettingRow>

        <NyxSettingRow title="Max tokens" description="Upper bound on a single reply.">
          <NyxTextField
            type="number"
            value={cfg.maxTokens}
            onChange={(e) => void patch({ maxTokens: Math.max(64, Number(e.target.value) || 64) })}
          />
        </NyxSettingRow>

        <NyxSettingRow title="Temperature" description="Lower is more deterministic. 0.2 suits code work.">
          <NyxTextField
            type="number"
            step="0.1"
            value={cfg.temperature}
            onChange={(e) => void patch({ temperature: Math.min(2, Math.max(0, Number(e.target.value) || 0)) })}
          />
        </NyxSettingRow>
      </div>
    </NyxCard>
  )
}

/**
 * A user-defined OpenAI-compatible endpoint: any URL, optional API key, and a
 * model list the user declares when the server has no /models route.
 */
function CustomProvider({
  cfg, onPatch, onProbe,
}: {
  cfg: AIConfig
  onPatch: (p: Partial<AIConfig>) => Promise<void>
  onProbe: () => Promise<void>
}) {
  const [keyDraft, setKeyDraft] = useState('')
  const [modelDraft, setModelDraft] = useState('')
  const [headerKey, setHeaderKey] = useState('')
  const [headerValue, setHeaderValue] = useState('')
  const [encrypted, setEncrypted] = useState<boolean | null>(null)
  const [saving, setSaving] = useState(false)

  useEffect(() => { void window.nyx.ai.secretsEncrypted().then(setEncrypted) }, [])

  const c = cfg.custom
  const setCustom = (patch: Partial<CustomProviderConfig>) => onPatch({ custom: { ...c, ...patch } })

  const saveKey = async (value: string | null) => {
    setSaving(true)
    await window.nyx.ai.setCustomKey(value)
    setKeyDraft('')
    await onPatch({})        // re-read the config so hasKey refreshes
    await onProbe()
    setSaving(false)
  }

  return (
    <div style={{ borderColor: nyx('outlineVariant') }} className="border-b py-3">
      <div style={{ color: nyx('textPrimary') }} className="mb-1 text-sm">Custom endpoint</div>
      <p style={{ color: nyx('textMuted') }} className="mb-3 text-xs">
        Any OpenAI-compatible API — a server on your LAN, a self-hosted gateway, or a remote
        provider. Nyxium's local backends stay the default; this one is only used when you select it.
      </p>

      <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
        <NyxTextField
          label="Name"
          value={c.label}
          placeholder="Workstation llama.cpp"
          onChange={(e) => void setCustom({ label: e.target.value })}
        />
        <NyxTextField
          label="Base URL"
          value={c.url}
          placeholder="http://10.0.0.5:8000/v1"
          onChange={(e) => void setCustom({ url: e.target.value })}
        />
      </div>

      <div className="mt-3">
        <div style={{ color: nyx('textSecondary') }} className="mb-1 text-xs font-medium">API key</div>
        <div className="flex items-end gap-2">
          <input
            type="password"
            value={keyDraft}
            onChange={(e) => setKeyDraft(e.target.value)}
            placeholder={c.hasKey ? '•••••••••• stored' : 'Leave empty if the endpoint needs no key'}
            autoComplete="off"
            style={{ background: nyx('surfaceVariant'), color: nyx('textPrimary'), borderColor: nyx('outlineVariant') }}
            className="h-9 min-w-0 flex-1 rounded-lg border px-2.5 text-sm outline-none
                       focus:border-[var(--nyx-primary)] placeholder:text-[var(--nyx-textMuted)]"
          />
          <NyxButton size="sm" loading={saving} disabled={!keyDraft.trim()} onClick={() => void saveKey(keyDraft)}>
            Save key
          </NyxButton>
          {c.hasKey ? (
            <NyxButton size="sm" variant="ghost" onClick={() => void saveKey(null)}>Remove</NyxButton>
          ) : null}
        </div>
        <p style={{ color: nyx('textMuted') }} className="mt-1.5 text-[11px]">
          {encrypted === null ? 'Checking credential storage…'
            : encrypted
              ? 'Stored encrypted in your OS keyring, outside the config file. The renderer never receives it.'
              : 'No OS keyring is available on this system, so the key is stored obfuscated in ~/.local/share/nyxium with 0600 permissions — not encrypted.'}
        </p>
      </div>

      <div className="mt-3 grid grid-cols-1 gap-2.5 sm:grid-cols-2">
        <NyxTextField
          label="Auth header"
          value={c.authHeader}
          placeholder="Authorization"
          onChange={(e) => void setCustom({ authHeader: e.target.value })}
        />
        <NyxTextField
          label="Auth scheme"
          value={c.authScheme}
          hint="Sent as “<scheme> <key>”. Clear it to send the raw key."
          placeholder="Bearer"
          onChange={(e) => void setCustom({ authScheme: e.target.value })}
        />
      </div>

      <div className="mt-3">
        <div style={{ color: nyx('textSecondary') }} className="mb-1 text-xs font-medium">Models</div>
        <p style={{ color: nyx('textMuted') }} className="mb-2 text-[11px]">
          Models are read from the endpoint's /models route. Add them here when it does not have one.
        </p>
        <div className="mb-2 flex flex-wrap gap-1.5">
          {c.models.map((m) => (
            <NyxChip key={m} onRemove={() => void setCustom({ models: c.models.filter((x) => x !== m) })}>
              {m}
            </NyxChip>
          ))}
          {!c.models.length ? (
            <span style={{ color: nyx('textMuted') }} className="text-[11px]">None declared.</span>
          ) : null}
        </div>
        <form
          onSubmit={(e) => {
            e.preventDefault()
            const m = modelDraft.trim()
            if (!m || c.models.includes(m)) return
            void setCustom({ models: [...c.models, m] })
            setModelDraft('')
          }}
          className="flex gap-2"
        >
          <input
            value={modelDraft}
            onChange={(e) => setModelDraft(e.target.value)}
            placeholder="model id, e.g. qwen2.5-coder-7b"
            style={{ background: nyx('surfaceVariant'), color: nyx('textPrimary'), borderColor: nyx('outlineVariant') }}
            className="h-8 min-w-0 flex-1 rounded-lg border px-2.5 font-mono text-xs outline-none
                       focus:border-[var(--nyx-primary)] placeholder:text-[var(--nyx-textMuted)]"
          />
          <NyxButton size="sm" type="submit" disabled={!modelDraft.trim()}>Add</NyxButton>
        </form>
      </div>

      <div className="mt-3">
        <div style={{ color: nyx('textSecondary') }} className="mb-1 text-xs font-medium">Extra headers</div>
        <div className="mb-2 flex flex-wrap gap-1.5">
          {Object.entries(c.headers).map(([k, v]) => (
            <NyxChip
              key={k}
              onRemove={() => {
                const next = { ...c.headers }
                delete next[k]
                void setCustom({ headers: next })
              }}
            >
              {k}: {v.length > 18 ? `${v.slice(0, 18)}…` : v}
            </NyxChip>
          ))}
          {!Object.keys(c.headers).length ? (
            <span style={{ color: nyx('textMuted') }} className="text-[11px]">None.</span>
          ) : null}
        </div>
        <form
          onSubmit={(e) => {
            e.preventDefault()
            if (!headerKey.trim() || !headerValue.trim()) return
            void setCustom({ headers: { ...c.headers, [headerKey.trim()]: headerValue.trim() } })
            setHeaderKey('')
            setHeaderValue('')
          }}
          className="flex gap-2"
        >
          <input
            value={headerKey}
            onChange={(e) => setHeaderKey(e.target.value)}
            placeholder="Header"
            style={{ background: nyx('surfaceVariant'), color: nyx('textPrimary'), borderColor: nyx('outlineVariant') }}
            className="h-8 w-40 rounded-lg border px-2.5 font-mono text-xs outline-none focus:border-[var(--nyx-primary)]"
          />
          <input
            value={headerValue}
            onChange={(e) => setHeaderValue(e.target.value)}
            placeholder="Value"
            style={{ background: nyx('surfaceVariant'), color: nyx('textPrimary'), borderColor: nyx('outlineVariant') }}
            className="h-8 min-w-0 flex-1 rounded-lg border px-2.5 font-mono text-xs outline-none focus:border-[var(--nyx-primary)]"
          />
          <NyxButton size="sm" type="submit" disabled={!headerKey.trim() || !headerValue.trim()}>Add</NyxButton>
        </form>
      </div>

      {cfg.provider === 'custom' ? (
        <p style={{ color: nyx('warning') }} className="mt-3 text-[11px]">
          This endpoint is selected, so prompts and any files the agent reads are sent to {c.url || 'it'}.
          Switch back to a local backend to keep everything on this machine.
        </p>
      ) : null}
    </div>
  )
}

function Row({ label, value, span }: { label: string; value: string; span?: boolean }) {
  return (
    <div className={`flex items-baseline justify-between gap-2 ${span ? 'col-span-2' : ''}`}>
      <span style={{ color: nyx('textSecondary') }}>{label}</span>
      <span style={{ color: nyx('textPrimary') }} className="truncate font-mono">{value}</span>
    </div>
  )
}
